version: 2

exposures:
  - name: secret
    type: application
    owner:
      name: Burak
      email: burak@email.com
    meta:
      jinjat:
        refine:
          menu_icon: heroicons/hand_raised
          actions:
            delete: _delete_secret
          resources:
            create: _create_secret
            list: _list_secret
            show: _get_secret
            edit: _edit_secret
          props:
            list:
              datagrid:
                initialState:
                  columns:
                    columnVisibilityModel:
                      status: false

analyses:
  - name: _create_secret
    config:
      tags: [secret]
      jinjat: 
        method: post
        response:
          content:
            $ref: analysis._show_secret
  - name: _list_secret
    config:
      tags: [secret]
      jinjat: 
        request:
          method: get
          body:
            $ref: analysis._show_secret
  - name: _edit_secret
    config:
      tags: [secret]
      jinjat: 
        request:
          method: patch
          body:
            $ref: analysis._show_secret
  - name: _show_secret
    config:
      tags: [secret]
    columns:
      - name: created_on
        data_type: timestamp
      - name: name
        data_type: string
      - name: schema_name
        data_type: string
      - name: database_name
        data_type: string
      - name: owner
        data_type: string
      - name: comment
        data_type: string
      - name: secret_type
        data_type: string
      - name: oauth_scopes
        data_type: string
    