version: 2

exposures:
  - name: procedures
    type: application
    owner:
      name: Burak
      email: burak@email.com
    meta:
      jinjat:
        refine:
          menu_icon: heroicons/code_bracket_square
          resources:
            list: _list_procedures
            show: _show_procedure
          actions:
            trigger: trigger_procedure
          props:
            list:
              datagrid:
                disableColumnSelector: true
                initialState:
                  columns:
                    columnVisibilityModel:
                      PROCEDURE_NAME: true
                      PROCEDURE_LANGUAGE: true
                      PROCEDURE_DEFINITION: false
                      PROCEDURE_OWNER: false
                      ARGUMENT_SIGNATURE: false
                      DATA_TYPE: false
                      CHARACTER_MAXIMUM_LENGTH: false
                      CHARACTER_OCTET_LENGTH: false
                      NUMERIC_PRECISION: false
                      NUMERIC_PRECISION_RADIX: false
                      NUMERIC_SCALE: false
                      CREATED: true
                      LAST_ALTERED: true
                      COMMENT: false

                    
analyses:
  - name: _list_procedures
    description: "Show a procedure"
    config:
      tags: [procedure]
      jinjat:
        method: get
        response:
          content:
            $ref: analysis._show_procedure
  - name: _show_procedure
    description: "Show a procedure"
    config:
      tags: [procedure]
      jinjat:
        method: get
        response:
          transform: "[0]"
          content:
            $ref: analysis._show_procedure
        schema:
          x-pk: PROCEDURE_NAME
    columns:
      - name: PROCEDURE_NAME
        description: "Schename and name of the stored procedure."
        data_type: TEXT
      - name: PROCEDURE_LANGUAGE
        description: "Language of the stored procedure."
        data_type: TEXT
      - name: PROCEDURE_DEFINITION
        description: "Stored procedure definition."
        data_type: TEXT
        meta:
          jinjat:
            schema:
              x-jsonforms:
                renderer: code
      - name: PROCEDURE_OWNER
        description: "Name of the role that owns the stored procedure."
        data_type: TEXT
      - name: ARGUMENT_SIGNATURE
        description: "Type signature of the stored procedure’s arguments."
        data_type: TEXT
      - name: DATA_TYPE
        description: "Return value data type."
        data_type: TEXT
      - name: CHARACTER_MAXIMUM_LENGTH
        description: "Maximum length in characters of string return value."
        data_type: NUMBER
      - name: CHARACTER_OCTET_LENGTH
        description: "Maximum length in bytes of string return value."
        data_type: NUMBER
      - name: NUMERIC_PRECISION
        description: "Numeric precision of numeric return value."
        data_type: NUMBER
      - name: NUMERIC_PRECISION_RADIX
        description: "Radix of precision of numeric return value."
        data_type: NUMBER
      - name: NUMERIC_SCALE
        description: "Scale of numeric return value."
        data_type: NUMBER
      - name: CREATED
        description: "Creation time of the stored procedure."
        data_type: TIMESTAMP_LTZ
      - name: LAST_ALTERED
        description: "Date and time the object was last altered."
        data_type: TIMESTAMP_LTZ
      - name: COMMENT
        description: "Comment for this stored procedure."
        data_type: TEXT

  - name: _trigger_procedure
    description: Trigger a procedure
    config:
      tags: [procedure]
      jinjat:
        method: put
        response:
          content:
            description: Returns the called procedure, the response is defined in the procedure signature
        request:
          body:
            type: object
            description: The procedure function signature
