version: 2

exposures:
  - name: roles
    type: application
    owner:
      name: Burak
      email: burak@email.com
    meta:
      jinjat:
        refine:
          menu_icon: heroicons/eye_slash
          resources:
            list: _list_roles
            show: _show_role
            create: _create_role
        props:
            list:
              datagrid:
                initialState:
                  columns:
                    columnVisibilityModel:
                      status: false


analyses:
  - name: _create_role
    config:
      tags: [role]
      jinjat:
  - name: _list_roles
    config:
      tags: [role]
      jinjat: 
  - name: _edit_role
    config:
      tags: [role]
      jinjat: 
  - name: _show_role
    config:
      tags: [role]
      jinjat: 