version: 2

exposures:
  - name: roles
    type: application
    owner:
      name: Burak
      email: burak@email.com
    meta:
      jinjat:
        refine:
          menu_icon: heroicons/user_group
          resources:
            list: _list_roles
            show: _show_role
          actions:
            show_users: show_users_has_role
        props:
            list:
              datagrid:
                initialState:
                  columns:
                    columnVisibilityModel:
                      status: false