version: 2

exposures:
  - name: notification_integration
    type: application
    owner:
      name: Burak
      email: burak@email.com
    meta:
      jinjat:
        refine:
          menu_icon: heroicons/arrow_right_on_rectangle
          actions:
            delete: _delete_notification_integration
          resources:
            create: _create_notification_integration
            list: _list_notification_integration
            show: _get_notification_integration
            edit: _edit_notification_integration
          props:
            list:
              datagrid:
                initialState:
                  columns:
                    columnVisibilityModel:
                      status: false

analyses:
  - name: _create_notification_integration
    config:
      tags: [notification_integration]
      jinjat: 
        response:
          content:
            $ref: analysis._show_notification_integration
  - name: _list_notification_integration
    config:
      tags: [notification_integration]
      jinjat: 
        request:
          body:
            $ref: analysis._show_notification_integration
  - name: _edit_notification_integration
    config:
      tags: [notification_integration]
      jinjat: 
        request:
          body:
            $ref: analysis._show_notification_integration
  - name: _show_notification_integration
    config:
      tags: [notification_integration]
      jinjat: 
        request:
    columns:
      - name: name
        description: Name of the integration
        data_type: string
      - name: type
        description: Type of the integration
        data_type: string
      - name: category
        description: Category of the integration
        data_type: string
      - name: enabled
        description: Current status of the integration, either TRUE (enabled) or FALSE (disabled)
        data_type: boolean
      - name: comment
        description: Comment for the integration
        data_type: string
      - name: created_on
        description: Date and time when the integration was created
        data_type: timestamp
      