version: 2

exposures:
  - name: alerts
    type: application
    owner:
      name: Burak
      email: burak@email.com
    meta:
      jinjat:
        refine:
          menu_icon: heroicons/bell
          actions:
            delete: _delete_alert
          resources:
            create: _create_alert
            list: _list_alert
            show: _show_alert
            edit: _edit_alert