version: 2

exposures:
  - name: tasks
    type: application
    owner:
      name: Burak
      email: burak@email.com
    meta:
      jinjat:
        refine:
          menu_icon: heroicons/archive_box
          actions:
            delete: _delete_task
            trigger: trigger_task
            history: task_history
          resources:
            create: _create_task
            list: _list_tasks
            show: _get_task
            edit: _edit_task
          props:
            list:
              datagrid:
                initialState:
                  columns:
                    columnVisibilityModel:
                      status: false
                      name: false
                      id: false
                      owner: false
                      database_name: false
                      predecessors: false
                      definition: false
                      condition: false
                      allow_overlapping_execution: false
                      error_integration: false
                      last_committed_on: false
                      created_on: false
                      comment: false

analyses:
  - name: _get_task
    description: "Get a task"
    config:
      tags: [task]
      jinjat:
        method: get
        response:
          content:
            $ref: analysis._get_task
          transform: "[0]"
    constraints:
      - type: primary_key
        columns: [name]
      - type: foreign_key
        expression: "ref('_list_warehouses')"
    columns:
      - name: created_on
        description: "The timestamp when the task was created"
        data_type: timestamp_ltz
        meta: &nonindexed
          jinjat:
            crud:
              filterable: false
              sortable: false
      - name: name
        description: "The name of the task"
        data_type: text
        meta:
          jinjat:
            crud:
              filterable: false
              sortable: false
            schema:
              x-pk: true
      - name: id
        description: "The unique identifier of the task"
        data_type: text
        constraints:
          - type: not_null
        meta: *nonindexed
      - name: database_name
        description: "The name of the database"
        data_type: string
        tests:
          - not_null
        meta: *nonindexed
      - name: schema_name
        description: "The name of the schema"
        data_type: text
        tests:
          - not_null
        meta: *nonindexed
      - name: owner
        description: "The owner of the task"
        data_type: text
        tests:
          - not_null
        meta: *nonindexed
      - name: comment
        description: "Additional comments about the task"
        data_type: string
        meta: *nonindexed
      - name: warehouse
        description: "The warehouse to run the task"
        data_type: text
        tests:
          - not_null
        meta:
          jinjat:
            crud:
              filterable: false
              sortable: false
            enum: _list_warehouses
      - name: schedule
        description: "The schedule of the task"
        data_type: text
        meta:
          jinjat:
            crud:
              filterable: false
              sortable: false
            schema:
              example: |
                USING CRON 0 1 1 1 1 America/Los_Angeles
      - name: predecessors
        description: "The list of predecessor tasks"
        data_type: text
        meta: *nonindexed
      - name: state
        description: "The state of the task"
        data_type: text
        tests:
          - not_null
        meta:
          example: "suspended"
      - name: definition
        description: "The SQL definition of the task"
        data_type: text
        meta:
          jinjat:
            crud:
              filterable: false
              sortable: false
            schema:
              x-jsonforms:
                renderer: code

      - name: condition
        description: "The condition for task execution"
        data_type: text
        meta: *nonindexed
      - name: allow_overlapping_execution
        description: "Whether overlapping execution is allowed"
        data_type: boolean
        meta: *nonindexed
      - name: error_integration
        description: "The integration for error reporting"
        data_type: text
        meta: *nonindexed
      - name: last_committed_on
        description: "The timestamp when the task was last committed"
        data_type: text
        meta: *nonindexed
      - name: last_suspended_on
        description: "The timestamp when the task was last suspended"
        data_type: timestamp_ltz
        meta: *nonindexed

  - name: _list_tasks
    description: "List tasks in the current database"
    config:
      tags: [task]
      jinjat:
        method: get
        request:
          parameters:
            - name: query
              in: query
              schema:
                type: text
              required: false
        response:
          content:
            $ref: analysis._get_task
  - name: _create_task
    description: "Create task"
    config:
      tags: [task]
      jinjat:
        method: post
        request:
          body:
            type: object
            properties:
              name:
                type: "string"
                description: "Name of the task."
              definition:
                type: "string"
                description: "SQL Definition of the task."
                x-jsonforms:
                  renderer: code
              warehouse:
                type: "string"
                description: "Warehouse where the task will be run."
                meta:
                  jinjat:
                    enum: _list_warehouses
              schedule:
                type: "string"
                description: "Cron schedule for the task."
              timezone:
                type: string
                default: "UTC"
                description: "Timezone for the task schedule. Defaults to UTC."
              config:
                type: "string"
                description: "Configuration settings for the task."
              timeout_ms:
                type: "integer"
                description: "Timeout for the task execution in milliseconds."
              comment:
                type: "string"
                description: "Comment or note about the task."
            required:
              - "name"
              - "schedule"
              - "allow_overlapping_execution"
              - "timeout_ms"
              - "suspect_after_num_tries"
              - "error_integration"
              - "definition"
        response:
          content:
            type: object
            properties:
              id:
                type: string
                optional: true
  - name: _delete_task
    description: "Delete task"
    config:
      tags: [task]
      jinjat:
        method: delete
        request:
          query:
            id:
              schema:
                type: string
              required: true
  - name: _edit_task
    description: "Edit exiting task"
    config:
      tags: [task]
      jinjat:
        method: post
        request:
          body:
            $ref: analysis._get_task
  - name: trigger_task
    description: "Execute the task manually"
    config:
      tags: [task]
      jinjat:
        method: put
        request:
          parameters:
            - name: query
              in: query
              schema:
                type: string
              required: true
  - name: task_history
    description: "The previous runs for the task"
    config:
      tags: [task]
      jinjat:
        method: put
        request:
          parameters:
            - name: query
              in: query
              schema:
                type: string
              required: true
      columns:
        - name: query_id
          description: "The unique identifier of the query"
        - name: name
          description: "The name of the query"
        - name: database_name
          description: "The name of the database"
        - name: schema_name
          description: "The name of the schema"
        - name: query_text
          description: "The SQL text of the query"
        - name: condition_text
          description: "The condition text of the query"
        - name: state
          description: "The state of the query"
          meta:
            example: "SUCCEEDED"
        - name: error_code
          description: "The error code, if the query failed"
        - name: error_message
          description: "The error message, if the query failed"
        - name: scheduled_time
          description: "The scheduled time of the query"
        - name: query_start_time
          description: "The start time of the query"
        - name: next_scheduled_time
          description: "The next scheduled time of the query"
        - name: completed_time
          description: "The completed time of the query"
        - name: root_task_id
          description: "The root task ID"
        - name: graph_version
          description: "The graph version"
        - name: run_id
          description: "The run ID of the query"
        - name: return_value
          description: "The return value of the query"
        - name: scheduled_from
          description: "The source of the scheduled task"
