version: 2

exposures:
  - name: views
    type: application
    owner:
      name: Burak
      email: burak@email.com
    meta:
      jinjat:
        refine:
          menu_icon: heroicons/table_cells
          resources:
            list: _list_views
            show: _show_view
            edit: _edit_view
            create: _create_view
          props:
            create:
              form:
                uischema:
            list:
              datagrid:
                initialState:
                  columns:
                    columnVisibilityModel:
                      REFERENCE: true
                      CREATED: true
                      LAST_DDL: false
                      LAST_DDL_BY: false
                      LAST_ALTERED: true
                      TABLE_OWNER: false
                      COLUMNS: false
                      TABLE_CATALOG: false
                      TABLE_SCHEMA: false
                      TABLE_NAME: false
                      VIEW_DEFINITION: false
                      CHECK_OPTION: false
                      IS_INSERTABLE_INTO: false
                      IS_TEMPORARY: false
                      IS_UPDATABLE: false
                      IS_SECURE: false
                      COMMENT: false

analyses:
  - name: _list_views
    description: "List views"
    config:
      tags: [relation]
      jinjat:
        method: get
        response:
          content:
            $ref: analysis._show_view
  - name: _create_view
    description: "Create view"
    config:
      tags: [relation]
      jinjat:
        method: post
        fetch: false
        request:
          body:
            $ref: analysis._show_view
  - name: _show_view
    description: "Show view"
    config:
      tags: [relation]
      jinjat:
        method: get
        response:
          content:
            $ref: analysis._show_view
          transform: "[0]"
    columns:
      - name: REFERENCE
        description: "Database that the table belongs to."
        data_type: TEXT
        meta:
          jinjat:
            schema:
              x-pk: true
      - name: TABLE_CATALOG
        description: "Database that the table belongs to."
        data_type: TEXT
      - name: TABLE_SCHEMA
        description: "Schema that the table belongs to."
        data_type: TEXT
      - name: TABLE_NAME
        description: "Name of the table."
        data_type: TEXT
      - name: TABLE_OWNER
        description: "Name of the role that owns the table."
        data_type: TEXT
      - name: VIEW_DEFINITION
        description: "SQL query for the view"
        meta:
          jinjat:
            schema:
              x-jsonforms:
                renderer: code
        data_type: TEXT
      - name: CHECK_OPTION
        data_type: TEXT
      - name: IS_SECURE
        data_type: TEXT
      - name: CREATED
        description: "Creation time of the table."
        data_type: TIMESTAMP_LTZ
      - name: LAST_ALTERED
        description: "Date and time when the table was last altered by a DDL or DML operation."
        data_type: TIMESTAMP_LTZ
        meta: &relativetime
          jinjat:
            schema:
              type: string
              x-jinjat-format: "relative"
              format: datetime
      - name: LAST_DDL
        description: "Timestamp of the last DDL operation performed on the table or view."
        data_type: TIMESTAMP_LTZ
        meta: *relativetime
      - name: LAST_DDL_BY
        description: "Username of the user who performed the last DDL operation on the table or view."
        data_type: TEXT
      - name: COMMENT
        description: "Comment for this table."
        data_type: TEXT
      - name: IS_TEMPORARY
        description: "Indicates whether this is a temporary table. Valid values are YES and NO."
        data_type: TEXT
        meta:
          jinjat:
            schema:
              type: string
              enum: [YES, NO]
      - name: COLUMNS
        description: "Columns in the table."
        data_type: VARIANT
        meta:
          jinjat:
            schema:
              type: array
              items:
                type: object
                required: [name, type]
                properties:
                  name:
                    type: string
                  type:
                    type: string
                    enum:
                      - NUMBER
                      - DECIMAL
                      - FLOAT
                      - DOUBLE
                      - TEXT
                      - VARCHAR
                      - BOOLEAN
                      - DATE
                      - DATETIME
                      - TIME
                      - VARIANT
                      - OBJECT
                      - ARRAY
                      - GEOGRAPHY
                      - GEOMETRY
                  nullable:
                    type: boolean
                  comment:
                    type: string
